
-- ================================================================
-- AMAN | أمان
-- V11 FINAL DATABASE - SINGLE FILE
-- Supabase / PostgreSQL
--
-- PURPOSE:
-- Build the AMAN database from an EMPTY Supabase project.
--
-- IMPORTANT:
-- 1) Run this file once on a NEW/EMPTY Supabase database.
-- 2) Supabase Auth remains authoritative for passwords/sessions.
-- 3) No service_role key belongs in Android.
-- 4) Critical mutations are performed through SECURITY DEFINER RPCs.
-- 5) Historical ledgers/audit/executions are append-only.
-- 6) External telecom payment is NOT automated by AMAN.
--
-- V11 closure decisions made for executable SQL:
-- - account_status: ACTIVE / SUSPENDED / DISABLED
-- - phone_number may belong to multiple customer_number relations.
-- - points ledger entry types are closed below.
-- - tariff modes use a direct configured value; tariff_mode determines
--   the duration unit.
-- - public codes are generated by database functions.
-- - app_content uses published versions; only one published version
--   per content_key is allowed.
-- - financial_account is included as a currency account/balance table.
-- ================================================================

begin;

create extension if not exists pgcrypto;

-- ================================================================
-- ENUMS
-- ================================================================

do $$ begin
  create type public.account_type as enum ('USER','SUBSCRIBER');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.account_status as enum ('ACTIVE','SUSPENDED','DISABLED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.admin_status as enum ('ACTIVE','SUSPENDED','DISABLED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.generic_status as enum ('ACTIVE','INACTIVE');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.purchase_status as enum ('PENDING','APPROVED','REJECTED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.protection_status as enum ('ACTIVE','EXPIRED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.tariff_mode as enum ('DAILY','WEEKLY','MONTHLY','YEARLY');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.customer_number_status as enum ('ACTIVE','INACTIVE','ARCHIVED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.points_direction as enum ('CREDIT','DEBIT');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.points_entry_type as enum (
    'PURCHASE_CREDIT',
    'ACTIVATION_DEBIT',
    'EXTENSION_DEBIT',
    'RENEWAL_DEBIT',
    'ADMIN_GRANT',
    'CORRECTION'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.task_status as enum ('OPEN','COMPLETED','CANCELLED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.task_execution_result as enum ('SUCCESS','FAILED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.financial_direction as enum ('INFLOW','OUTFLOW');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.financial_entry_type as enum (
    'POINTS_SALE',
    'TASK_EXPENSE',
    'OPERATING_EXPENSE',
    'ADJUSTMENT',
    'CORRECTION'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.conversation_status as enum ('OPEN','CLOSED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.sender_type as enum ('CUSTOMER','ADMIN');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.operation_status as enum ('STARTED','COMPLETED','FAILED','REJECTED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.actor_type as enum ('CUSTOMER','ADMIN','SYSTEM');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.notification_delivery_status as enum ('PENDING','SENT','FAILED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.notification_campaign_status as enum ('DRAFT','SENT','CANCELLED');
exception when duplicate_object then null; end $$;

-- ================================================================
-- COMMON FUNCTIONS
-- ================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.normalize_phone(p_phone text)
returns text
language sql
immutable
as $$
  select regexp_replace(coalesce(p_phone,''), '[^0-9]+', '', 'g');
$$;

create or replace function public.generate_public_code(p_prefix text)
returns text
language plpgsql
as $$
begin
  return upper(coalesce(p_prefix,'X')) || '-' ||
         to_char(clock_timestamp(),'YYMMDDHH24MISSMS') || '-' ||
         upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));
end;
$$;

create or replace function public.current_admin_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select ai.id
  from public.admin_identity ai
  join public.auth_account aa on aa.id = ai.auth_account_id
  where aa.auth_user_id = auth.uid()
    and ai.status = 'ACTIVE';
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.admin_identity ai
    join public.auth_account aa on aa.id = ai.auth_account_id
    where aa.auth_user_id = auth.uid()
      and ai.status = 'ACTIVE'
  );
$$;

create or replace function public.has_admin_permission(p_permission text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.admin_identity ai
    join public.auth_account aa on aa.id = ai.auth_account_id
    join public.admin_assignments ass on ass.admin_id = ai.id and ass.status = 'ACTIVE'
    join public.role_permissions rp on rp.role_id = ass.role_id
    join public.permissions p on p.id = rp.permission_id and p.status = 'ACTIVE'
    where aa.auth_user_id = auth.uid()
      and ai.status = 'ACTIVE'
      and p.code = p_permission
  );
$$;

-- ================================================================
-- AUTH / IDENTITY
-- ================================================================

create table public.auth_account (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.customer_profile (
  id uuid primary key default gen_random_uuid(),
  auth_account_id uuid not null unique references public.auth_account(id) on delete cascade,
  public_user_code text not null unique,
  name text not null,
  email text,
  account_type public.account_type not null default 'USER',
  account_status public.account_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.subscriber_identity (
  id uuid primary key default gen_random_uuid(),
  customer_profile_id uuid not null unique references public.customer_profile(id) on delete restrict,
  public_subscriber_code text not null unique,
  activated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.admin_identity (
  id uuid primary key default gen_random_uuid(),
  auth_account_id uuid not null unique references public.auth_account(id) on delete cascade,
  admin_code text not null unique,
  status public.admin_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.roles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.permissions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  domain text not null,
  action text not null,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now()
);

create table public.role_permissions (
  role_id uuid not null references public.roles(id) on delete cascade,
  permission_id uuid not null references public.permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

create table public.admin_assignments (
  admin_id uuid not null references public.admin_identity(id) on delete cascade,
  role_id uuid not null references public.roles(id) on delete restrict,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (admin_id, role_id)
);

-- ================================================================
-- TELECOM
-- ================================================================

create table public.telecom_company (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.telecom_prefix (
  id uuid primary key default gen_random_uuid(),
  telecom_company_id uuid not null references public.telecom_company(id) on delete restrict,
  prefix text not null,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (telecom_company_id, prefix),
  check (length(trim(prefix)) > 0)
);

create table public.protection_tariff (
  id uuid primary key default gen_random_uuid(),
  telecom_company_id uuid not null references public.telecom_company(id) on delete restrict,
  tariff_mode public.tariff_mode not null,
  rate numeric(14,2) not null check (rate >= 0),
  currency text not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_to > effective_from)
);

create table public.task_configuration (
  id uuid primary key default gen_random_uuid(),
  telecom_company_id uuid not null references public.telecom_company(id) on delete restrict,
  interval_days integer not null check (interval_days > 0),
  task_amount numeric(14,2) not null check (task_amount >= 0),
  currency text not null,
  visibility_days_before integer not null default 5 check (visibility_days_before >= 0),
  allow_reschedule boolean not null default true,
  allow_post_expiry_creation boolean not null default false,
  post_expiry_grace_days integer not null default 0 check (post_expiry_grace_days >= 0),
  create_first_task_on_activation boolean not null default true,
  create_first_task_on_renewal boolean not null default false,
  status public.generic_status not null default 'ACTIVE',
  effective_from timestamptz not null default now(),
  effective_to timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_to > effective_from)
);

-- ================================================================
-- NUMBERS
-- ================================================================

create table public.phone_number (
  id uuid primary key default gen_random_uuid(),
  normalized_phone text not null unique,
  display_phone text not null,
  telecom_company_id uuid not null references public.telecom_company(id) on delete restrict,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.customer_number (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  phone_number_id uuid not null references public.phone_number(id) on delete restrict,
  public_added_number_code text not null unique,
  status public.customer_number_status not null default 'ACTIVE',
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(customer_id, phone_number_id)
);

-- ================================================================
-- POINTS
-- ================================================================

create table public.points_package (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  points bigint not null check (points > 0),
  price numeric(14,2) not null check (price > 0),
  currency text not null,
  display_order integer not null default 0,
  is_visible boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.payment_method (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  type text not null,
  receiving_account text not null,
  transfer_instructions text,
  display_order integer not null default 0,
  is_visible boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.points_balance (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null unique references public.customer_profile(id) on delete restrict,
  balance bigint not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);

create table public.points_purchase (
  id uuid primary key default gen_random_uuid(),
  public_purchase_code text not null unique,
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  package_id uuid not null references public.points_package(id) on delete restrict,
  payment_method_id uuid not null references public.payment_method(id) on delete restrict,

  package_name_snapshot text not null,
  points_snapshot bigint not null check (points_snapshot > 0),
  price_snapshot numeric(14,2) not null check (price_snapshot > 0),
  currency_snapshot text not null,

  payment_method_name_snapshot text not null,
  receiving_account_snapshot text not null,
  payment_instructions_snapshot text,

  transfer_reference text not null,

  status public.purchase_status not null default 'PENDING',
  rejection_reason text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.admin_identity(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (
    status <> 'REJECTED'
    or nullif(trim(rejection_reason),'') is not null
  )
);

create table public.points_ledger (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  direction public.points_direction not null,
  amount bigint not null check (amount > 0),
  balance_before bigint not null check (balance_before >= 0),
  balance_after bigint not null check (balance_after >= 0),
  entry_type public.points_entry_type not null,
  source_type text,
  source_id uuid,
  description text,
  created_by uuid,
  created_at timestamptz not null default now(),
  check (
    (direction = 'CREDIT' and balance_after = balance_before + amount)
    or
    (direction = 'DEBIT' and balance_after = balance_before - amount)
  )
);

-- ================================================================
-- PROTECTION
-- ================================================================

create table public.number_protection_identity (
  id uuid primary key default gen_random_uuid(),
  customer_number_id uuid not null unique references public.customer_number(id) on delete restrict,
  public_activation_code text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.protection_period (
  id uuid primary key default gen_random_uuid(),
  protection_identity_id uuid not null references public.number_protection_identity(id) on delete restrict,
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  start_at timestamptz not null,
  end_at timestamptz not null,
  duration_days integer not null check (duration_days > 0),

  tariff_id uuid not null references public.protection_tariff(id) on delete restrict,
  tariff_mode_snapshot public.tariff_mode not null,
  tariff_value_snapshot numeric(14,2) not null check (tariff_value_snapshot >= 0),
  currency_snapshot text not null,
  points_cost_snapshot bigint not null check (points_cost_snapshot >= 0),

  status public.protection_status not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (end_at > start_at)
);

create table public.protection_extension (
  id uuid primary key default gen_random_uuid(),
  protection_period_id uuid not null references public.protection_period(id) on delete restrict,
  days_added integer not null check (days_added > 0),
  tariff_mode_snapshot public.tariff_mode not null,
  tariff_value_snapshot numeric(14,2) not null check (tariff_value_snapshot >= 0),
  currency_snapshot text not null,
  points_cost bigint not null check (points_cost > 0),
  balance_before bigint not null check (balance_before >= 0),
  balance_after bigint not null check (balance_after >= 0),
  operation_id uuid,
  created_at timestamptz not null default now()
);

-- ================================================================
-- TASKS
-- ================================================================

create table public.task_plan (
  id uuid primary key default gen_random_uuid(),
  protection_period_id uuid not null unique references public.protection_period(id) on delete restrict,
  task_configuration_id uuid not null references public.task_configuration(id) on delete restrict,
  status public.generic_status not null default 'ACTIVE',
  anchor_at timestamptz not null,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.periodic_task (
  id uuid primary key default gen_random_uuid(),
  public_task_code text not null unique,
  task_plan_id uuid not null references public.task_plan(id) on delete restrict,
  protection_period_id uuid not null references public.protection_period(id) on delete restrict,
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  customer_number_id uuid not null references public.customer_number(id) on delete restrict,
  telecom_company_id uuid not null references public.telecom_company(id) on delete restrict,

  sequence_no integer not null check (sequence_no > 0),
  planned_total integer,
  due_at timestamptz not null,

  amount numeric(14,2) not null check (amount >= 0),
  currency text not null,

  status public.task_status not null default 'OPEN',

  executed_at timestamptz,
  cancelled_at timestamptz,
  cancellation_reason text,

  company_snapshot text not null,
  amount_snapshot numeric(14,2) not null check (amount_snapshot >= 0),
  currency_snapshot text not null,
  interval_snapshot integer not null check (interval_snapshot > 0),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (status <> 'CANCELLED' or nullif(trim(cancellation_reason),'') is not null)
);

create table public.task_schedule_history (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.periodic_task(id) on delete restrict,
  old_due_at timestamptz not null,
  new_due_at timestamptz not null,
  reason text,
  changed_by uuid,
  created_at timestamptz not null default now()
);

create table public.task_execution (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null unique references public.periodic_task(id) on delete restrict,
  execution_result public.task_execution_result not null,
  external_reference text,
  executed_at timestamptz not null default now(),
  executed_by uuid not null,
  amount numeric(14,2),
  currency text,
  created_at timestamptz not null default now()
);

-- ================================================================
-- FINANCE
-- ================================================================

create table public.financial_account (
  id uuid primary key default gen_random_uuid(),
  currency text not null unique,
  balance numeric(14,2) not null default 0,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (balance >= 0)
);

create table public.expense_type (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  status public.generic_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.financial_ledger (
  id uuid primary key default gen_random_uuid(),
  entry_type public.financial_entry_type not null,
  direction public.financial_direction not null,
  amount numeric(14,2) not null check (amount >= 0),
  currency text not null,
  source_type text,
  source_id uuid,
  description text,
  created_by uuid,
  created_at timestamptz not null default now()
);

create table public.expense (
  id uuid primary key default gen_random_uuid(),
  expense_type_id uuid not null references public.expense_type(id) on delete restrict,
  amount numeric(14,2) not null check (amount > 0),
  currency text not null,
  description text not null,
  reference text,
  posted_by uuid not null,
  posted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.financial_correction (
  id uuid primary key default gen_random_uuid(),
  original_ledger_entry_id uuid not null references public.financial_ledger(id) on delete restrict,
  correction_ledger_entry_id uuid not null references public.financial_ledger(id) on delete restrict,
  reason text not null,
  created_by uuid not null,
  created_at timestamptz not null default now()
);

-- ================================================================
-- COMMUNICATION
-- ================================================================

create table public.support_conversation (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  subject text,
  status public.conversation_status not null default 'OPEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_by uuid
);

create table public.support_message (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.support_conversation(id) on delete restrict,
  sender_type public.sender_type not null,
  sender_id uuid not null,
  body text not null,
  sent_at timestamptz not null default now(),
  read_at timestamptz
);

create table public.admin_message_thread (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  status public.conversation_status not null default 'OPEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.admin_message (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.admin_message_thread(id) on delete restrict,
  sender_admin_id uuid not null references public.admin_identity(id) on delete restrict,
  body text not null,
  sent_at timestamptz not null default now(),
  read_at timestamptz
);

-- ================================================================
-- NOTIFICATIONS
-- ================================================================

create table public.notification_event (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  source_type text,
  source_id uuid,
  created_at timestamptz not null default now()
);

create table public.customer_notification (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  event_id uuid references public.notification_event(id) on delete restrict,
  notification_type text not null,
  title text not null,
  body text not null,
  reference_type text,
  reference_id uuid,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table public.admin_notification_campaign (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references public.admin_identity(id) on delete restrict,
  target_type text not null,
  target_definition jsonb not null default '{}'::jsonb,
  title text not null,
  body text not null,
  status public.notification_campaign_status not null default 'DRAFT',
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create table public.admin_notification_recipient (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.admin_notification_campaign(id) on delete restrict,
  customer_id uuid not null references public.customer_profile(id) on delete restrict,
  delivery_status public.notification_delivery_status not null default 'PENDING',
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique(campaign_id, customer_id)
);

-- ================================================================
-- OPERATIONS / IDEMPOTENCY / AUDIT
-- ================================================================

create table public.operation (
  id uuid primary key default gen_random_uuid(),
  operation_key text not null unique,
  operation_type text not null,
  actor_type public.actor_type not null,
  actor_id uuid,
  entity_type text not null,
  entity_id uuid not null,
  status public.operation_status not null default 'STARTED',
  idempotency_key text,
  result_reference text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.operation_idempotency (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid,
  operation_type text not null,
  idempotency_key text not null,
  operation_id uuid not null references public.operation(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(actor_id, operation_type, idempotency_key)
);

create table public.audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_type public.actor_type not null,
  actor_id uuid,
  operation_id uuid references public.operation(id) on delete restrict,
  entity_type text not null,
  entity_id uuid not null,
  action text not null,
  permission_code text,
  before_state jsonb,
  after_state jsonb,
  reason text,
  created_at timestamptz not null default now()
);

-- ================================================================
-- CONTENT / SYSTEM
-- ================================================================

create table public.app_content (
  id uuid primary key default gen_random_uuid(),
  content_key text not null,
  version integer not null check(version > 0),
  title text not null,
  body text not null,
  status public.generic_status not null default 'INACTIVE',
  created_by uuid,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  unique(content_key, version)
);

create table public.maintenance_config (
  id uuid primary key default gen_random_uuid(),
  enabled boolean not null default false,
  customer_message text,
  updated_by uuid,
  updated_at timestamptz not null default now(),
  singleton_key boolean not null default true unique
);

insert into public.maintenance_config(enabled, customer_message)
values(false, null)
on conflict(singleton_key) do nothing;

-- ================================================================
-- INDEXES
-- ================================================================

create index idx_customer_profile_status on public.customer_profile(account_status);
create index idx_customer_profile_type on public.customer_profile(account_type);
create index idx_customer_number_customer on public.customer_number(customer_id);
create index idx_customer_number_phone on public.customer_number(phone_number_id);
create index idx_phone_company on public.phone_number(telecom_company_id);
create index idx_prefix_company on public.telecom_prefix(telecom_company_id);
create index idx_prefix_value on public.telecom_prefix(prefix);
create index idx_tariff_company_effective on public.protection_tariff(telecom_company_id,effective_from desc);
create index idx_task_config_company_effective on public.task_configuration(telecom_company_id,effective_from desc);
create index idx_purchase_customer_status on public.points_purchase(customer_id,status);
create index idx_purchase_status_submitted on public.points_purchase(status,submitted_at desc);
create index idx_points_ledger_customer_date on public.points_ledger(customer_id,created_at desc);
create index idx_protection_customer_status on public.protection_period(customer_id,status);
create index idx_protection_identity_status on public.protection_period(protection_identity_id,status);
create index idx_extension_period on public.protection_extension(protection_period_id,created_at desc);
create index idx_task_plan_protection on public.task_plan(protection_period_id);
create index idx_task_due_status on public.periodic_task(status,due_at);
create index idx_task_customer_due on public.periodic_task(customer_id,due_at);
create index idx_task_number_due on public.periodic_task(customer_number_id,due_at);
create index idx_task_company_due on public.periodic_task(telecom_company_id,due_at);
create index idx_task_schedule_task on public.task_schedule_history(task_id,created_at desc);
create index idx_task_execution_date on public.task_execution(executed_at desc);
create index idx_financial_ledger_date on public.financial_ledger(created_at desc);
create index idx_financial_ledger_source on public.financial_ledger(source_type,source_id);
create index idx_expense_date on public.expense(posted_at desc);
create index idx_support_customer on public.support_conversation(customer_id,updated_at desc);
create index idx_support_messages_conversation on public.support_message(conversation_id,sent_at);
create index idx_admin_thread_customer on public.admin_message_thread(customer_id,updated_at desc);
create index idx_notifications_customer on public.customer_notification(customer_id,created_at desc);
create index idx_notifications_unread on public.customer_notification(customer_id,is_read,created_at desc);
create index idx_campaign_recipients_customer on public.admin_notification_recipient(customer_id);
create index idx_operation_entity on public.operation(entity_type,entity_id,created_at desc);
create index idx_operation_actor on public.operation(actor_id,created_at desc);
create index idx_audit_entity on public.audit_log(entity_type,entity_id,created_at desc);

create unique index uq_active_protection_identity
on public.protection_period(protection_identity_id)
where status = 'ACTIVE';

create unique index uq_published_content
on public.app_content(content_key)
where status = 'ACTIVE';

-- ================================================================
-- UPDATED_AT TRIGGERS
-- ================================================================

do $$
declare t text;
begin
  foreach t in array array[
    'auth_account','customer_profile','subscriber_identity','admin_identity',
    'roles','admin_assignments','telecom_company','telecom_prefix',
    'protection_tariff','task_configuration','phone_number','customer_number',
    'points_package','payment_method','points_balance','points_purchase',
    'number_protection_identity','protection_period','task_plan','periodic_task',
    'financial_account','expense_type','support_conversation',
    'admin_message_thread','app_content'
  ]
  loop
    execute format(
      'drop trigger if exists trg_%s_updated_at on public.%I;
       create trigger trg_%s_updated_at
       before update on public.%I
       for each row execute function public.set_updated_at();',
      t,t,t,t
    );
  end loop;
end $$;

-- ================================================================
-- SEED PERMISSIONS / ROLES
-- ================================================================

insert into public.roles(code,name) values
('SUPER_ADMIN','Super Admin'),
('OPERATIONS','Operations'),
('FINANCE','Finance'),
('SUPPORT','Support')
on conflict(code) do nothing;

insert into public.permissions(code,name,domain,action) values
('customers.read','قراءة العملاء','customers','read'),
('customers.update','تحديث العملاء','customers','update'),
('users.read','قراءة المستخدمين','users','read'),
('users.update','تحديث المستخدمين','users','update'),
('numbers.read','قراءة الأرقام','numbers','read'),
('numbers.update','إدارة الأرقام','numbers','update'),
('points_purchases.read','قراءة مشتريات النقاط','points_purchases','read'),
('points_purchases.approve','اعتماد مشتريات النقاط','points_purchases','approve'),
('points_purchases.reject','رفض مشتريات النقاط','points_purchases','reject'),
('tasks.read','قراءة المهام','tasks','read'),
('tasks.execute','تنفيذ المهام','tasks','execute'),
('tasks.reschedule','إعادة جدولة المهام','tasks','reschedule'),
('tasks.cancel','إلغاء المهام','tasks','cancel'),
('providers.read','قراءة الشركات','providers','read'),
('providers.write','إدارة الشركات','providers','write'),
('packages.read','قراءة الباقات','packages','read'),
('packages.write','إدارة الباقات','packages','write'),
('payment_methods.read','قراءة وسائل الدفع','payment_methods','read'),
('payment_methods.write','إدارة وسائل الدفع','payment_methods','write'),
('task_settings.read','قراءة إعدادات المهام','task_settings','read'),
('task_settings.write','إدارة إعدادات المهام','task_settings','write'),
('notifications.read','قراءة الإشعارات','notifications','read'),
('notifications.send','إرسال الإشعارات','notifications','send'),
('reports.read','قراءة التقارير','reports','read'),
('finance.read','قراءة المالية','finance','read'),
('finance.write','إدارة المالية','finance','write'),
('audit.read','قراءة التدقيق','audit','read'),
('roles.manage','إدارة الصلاحيات','roles','manage'),
('support.write','إدارة الدعم','support','write'),
('system.maintenance','إدارة الصيانة','system','maintenance')
on conflict(code) do nothing;

insert into public.role_permissions(role_id,permission_id)
select r.id,p.id
from public.roles r cross join public.permissions p
where r.code='SUPER_ADMIN'
on conflict do nothing;

insert into public.role_permissions(role_id,permission_id)
select r.id,p.id
from public.roles r cross join public.permissions p
where r.code='OPERATIONS'
and p.code in (
 'customers.read','numbers.read','numbers.update','tasks.read',
 'tasks.execute','tasks.reschedule','tasks.cancel','providers.read',
 'packages.read','payment_methods.read','task_settings.read',
 'notifications.read','reports.read','support.write'
)
on conflict do nothing;

insert into public.role_permissions(role_id,permission_id)
select r.id,p.id
from public.roles r cross join public.permissions p
where r.code='FINANCE'
and p.code in (
 'customers.read','points_purchases.read','points_purchases.approve',
 'points_purchases.reject','finance.read','finance.write','reports.read',
 'audit.read'
)
on conflict do nothing;

insert into public.role_permissions(role_id,permission_id)
select r.id,p.id
from public.roles r cross join public.permissions p
where r.code='SUPPORT'
and p.code in ('customers.read','users.read','support.write','notifications.read')
on conflict do nothing;

-- ================================================================
-- PROFILE PROVISIONING
-- ================================================================

create or replace function public.create_customer_profile(
  p_name text,
  p_email text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  aa public.auth_account;
  cp public.customer_profile;
  pb public.points_balance;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;

  insert into public.auth_account(auth_user_id)
  values(auth.uid())
  on conflict(auth_user_id) do update set updated_at=now()
  returning * into aa;

  insert into public.customer_profile(
    auth_account_id,public_user_code,name,email
  )
  values(
    aa.id,public.generate_public_code('U'),trim(p_name),p_email
  )
  on conflict(auth_account_id)
  do update set name=excluded.name,email=excluded.email,updated_at=now()
  returning * into cp;

  insert into public.points_balance(customer_id)
  values(cp.id)
  on conflict(customer_id) do nothing
  returning * into pb;

  return jsonb_build_object(
    'customer_id',cp.id,
    'public_user_code',cp.public_user_code,
    'account_type',cp.account_type,
    'account_status',cp.account_status
  );
end;
$$;

create or replace function public.ensure_auth_account()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare v_id uuid;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;

  insert into public.auth_account(auth_user_id)
  values(auth.uid())
  on conflict(auth_user_id) do update set updated_at=now()
  returning id into v_id;

  return v_id;
end;
$$;

-- ================================================================
-- ADD NUMBER
-- ================================================================

create or replace function public.add_customer_number(
  p_phone text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_account_id uuid;
  v_customer_id uuid;
  v_phone text;
  v_company_id uuid;
  v_phone_id uuid;
  v_cn public.customer_number;
begin
  v_auth_account_id := public.ensure_auth_account();

  select id into v_customer_id
  from public.customer_profile
  where auth_account_id=v_auth_account_id
    and account_status='ACTIVE'
  for update;

  if v_customer_id is null then raise exception 'CUSTOMER_NOT_FOUND'; end if;

  if nullif(trim(p_idempotency_key),'') is null then
    raise exception 'IDEMPOTENCY_KEY_REQUIRED';
  end if;

  v_phone := public.normalize_phone(p_phone);

  if length(v_phone) < 7 then raise exception 'INVALID_PHONE'; end if;

  select telecom_company_id into v_company_id
  from public.telecom_prefix
  where status='ACTIVE'
    and v_phone like prefix || '%'
  order by length(prefix) desc
  limit 1;

  if v_company_id is null then raise exception 'TELECOM_COMPANY_NOT_DETECTED'; end if;

  insert into public.phone_number(
    normalized_phone,display_phone,telecom_company_id
  )
  values(v_phone,p_phone,v_company_id)
  on conflict(normalized_phone)
  do update set display_phone=excluded.display_phone,
                telecom_company_id=excluded.telecom_company_id,
                updated_at=now()
  returning id into v_phone_id;

  insert into public.customer_number(
    customer_id,phone_number_id,public_added_number_code,status
  )
  values(
    v_customer_id,v_phone_id,public.generate_public_code('N'),'ACTIVE'
  )
  on conflict(customer_id,phone_number_id)
  do update set status='ACTIVE',updated_at=now()
  returning * into v_cn;

  insert into public.operation(
    operation_key,operation_type,actor_type,actor_id,
    entity_type,entity_id,status,idempotency_key,completed_at
  )
  values(
    public.generate_public_code('OP'),'ADD_NUMBER','CUSTOMER',v_customer_id,
    'customer_number',v_cn.id,'COMPLETED',p_idempotency_key,now()
  );

  return jsonb_build_object(
    'customer_number_id',v_cn.id,
    'phone_number_id',v_phone_id,
    'status',v_cn.status
  );
end;
$$;

-- ================================================================
-- SUBMIT POINTS PURCHASE
-- ================================================================

create or replace function public.submit_points_purchase(
  p_package_id uuid,
  p_payment_method_id uuid,
  p_transfer_reference text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_aa uuid;
  v_customer_id uuid;
  v_package public.points_package;
  v_method public.payment_method;
  v_purchase public.points_purchase;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if nullif(trim(p_idempotency_key),'') is null then raise exception 'IDEMPOTENCY_KEY_REQUIRED'; end if;
  if nullif(trim(p_transfer_reference),'') is null then raise exception 'PAYMENT_REFERENCE_REQUIRED'; end if;

  select id into v_aa from public.auth_account where auth_user_id=auth.uid();
  select id into v_customer_id from public.customer_profile
  where auth_account_id=v_aa and account_status='ACTIVE';

  if v_customer_id is null then raise exception 'CUSTOMER_NOT_FOUND'; end if;

  select * into v_package
  from public.points_package
  where id=p_package_id and is_active=true and is_visible=true;

  if v_package.id is null then raise exception 'PACKAGE_NOT_AVAILABLE'; end if;

  select * into v_method
  from public.payment_method
  where id=p_payment_method_id and is_active=true and is_visible=true;

  if v_method.id is null then raise exception 'PAYMENT_METHOD_NOT_AVAILABLE'; end if;

  if exists(
    select 1 from public.points_purchase
    where customer_id=v_customer_id
      and transfer_reference=trim(p_transfer_reference)
      and status in ('PENDING','APPROVED')
  ) then
    raise exception 'PAYMENT_REFERENCE_ALREADY_USED';
  end if;

  insert into public.points_purchase(
    public_purchase_code,customer_id,package_id,payment_method_id,
    package_name_snapshot,points_snapshot,price_snapshot,currency_snapshot,
    payment_method_name_snapshot,receiving_account_snapshot,
    payment_instructions_snapshot,transfer_reference
  )
  values(
    public.generate_public_code('P'),
    v_customer_id,v_package.id,v_method.id,
    v_package.name,v_package.points,v_package.price,v_package.currency,
    v_method.name,v_method.receiving_account,v_method.transfer_instructions,
    trim(p_transfer_reference)
  )
  returning * into v_purchase;

  insert into public.operation(
    operation_key,operation_type,actor_type,actor_id,
    entity_type,entity_id,status,idempotency_key,completed_at
  )
  values(
    public.generate_public_code('OP'),'PURCHASE_POINTS','CUSTOMER',v_customer_id,
    'points_purchase',v_purchase.id,'COMPLETED',p_idempotency_key,now()
  );

  return jsonb_build_object(
    'purchase_id',v_purchase.id,
    'purchase_code',v_purchase.public_purchase_code,
    'status',v_purchase.status
  );
end;
$$;

-- ================================================================
-- APPROVE PURCHASE
-- ================================================================

create or replace function public.approve_points_purchase(
  p_purchase_id uuid,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase public.points_purchase;
  v_balance public.points_balance;
  v_subscriber public.subscriber_identity;
  v_customer public.customer_profile;
  v_admin uuid;
  v_operation uuid;
begin
  if not public.has_admin_permission('points_purchases.approve') then
    raise exception 'FORBIDDEN';
  end if;

  if nullif(trim(p_idempotency_key),'') is null then
    raise exception 'IDEMPOTENCY_KEY_REQUIRED';
  end if;

  select * into v_purchase
  from public.points_purchase
  where id=p_purchase_id
  for update;

  if v_purchase.id is null then raise exception 'PURCHASE_NOT_FOUND'; end if;
  if v_purchase.status <> 'PENDING' then raise exception 'PURCHASE_NOT_PENDING'; end if;

  select * into v_customer
  from public.customer_profile
  where id=v_purchase.customer_id
  for update;

  insert into public.points_balance(customer_id)
  values(v_customer.id)
  on conflict(customer_id) do nothing;

  select * into v_balance
  from public.points_balance
  where customer_id=v_customer.id
  for update;

  update public.points_purchase
  set status='APPROVED',
      reviewed_at=now(),
      reviewed_by=public.current_admin_id(),
      updated_at=now()
  where id=v_purchase.id
  returning * into v_purchase;

  if not exists(
    select 1 from public.subscriber_identity
    where customer_profile_id=v_customer.id
  ) then
    insert into public.subscriber_identity(
      customer_profile_id,public_subscriber_code
    )
    values(v_customer.id,public.generate_public_code('S'))
    returning * into v_subscriber;
  else
    select * into v_subscriber
    from public.subscriber_identity
    where customer_profile_id=v_customer.id;
  end if;

  update public.customer_profile
  set account_type='SUBSCRIBER',updated_at=now()
  where id=v_customer.id;

  insert into public.points_ledger(
    customer_id,direction,amount,balance_before,balance_after,
    entry_type,source_type,source_id,description,created_by
  )
  values(
    v_customer.id,'CREDIT',v_purchase.points_snapshot,
    v_balance.balance,v_balance.balance+v_purchase.points_snapshot,
    'PURCHASE_CREDIT','points_purchase',v_purchase.id,
    'Approved points purchase',public.current_admin_id()
  );

  update public.points_balance
  set balance=balance+v_purchase.points_snapshot,updated_at=now()
  where id=v_balance.id;

  insert into public.financial_ledger(
    entry_type,direction,amount,currency,source_type,source_id,
    description,created_by
  )
  values(
    'POINTS_SALE','INFLOW',v_purchase.price_snapshot,v_purchase.currency_snapshot,
    'points_purchase',v_purchase.id,'Approved points purchase',public.current_admin_id()
  );

  insert into public.financial_account(currency,balance)
  values(v_purchase.currency_snapshot,v_purchase.price_snapshot)
  on conflict(currency)
  do update set balance=public.financial_account.balance+excluded.balance,
                updated_at=now();

  insert into public.operation(
    operation_key,operation_type,actor_type,actor_id,
    entity_type,entity_id,status,idempotency_key,completed_at
  )
  values(
    public.generate_public_code('OP'),'APPROVE_PURCHASE','ADMIN',
    public.current_admin_id(),'points_purchase',v_purchase.id,
    'COMPLETED',p_idempotency_key,now()
  )
  returning id into v_operation;

  insert into public.notification_event(event_type,source_type,source_id)
  values('POINTS_PURCHASE_APPROVED','points_purchase',v_purchase.id);

  insert into public.audit_log(
    actor_type,actor_id,operation_id,entity_type,entity_id,action,
    permission_code,after_state
  )
  values(
    'ADMIN',public.current_admin_id(),v_operation,
    'points_purchase',v_purchase.id,'APPROVE_PURCHASE',
    'points_purchases.approve',to_jsonb(v_purchase)
  );

  return jsonb_build_object(
    'purchase_id',v_purchase.id,
    'status',v_purchase.status,
    'subscriber_id',v_subscriber.id,
    'balance',v_balance.balance+v_purchase.points_snapshot
  );
end;
$$;

-- ================================================================
-- REJECT PURCHASE
-- ================================================================

create or replace function public.reject_points_purchase(
  p_purchase_id uuid,
  p_reason text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase public.points_purchase;
  v_operation uuid;
begin
  if not public.has_admin_permission('points_purchases.reject') then
    raise exception 'FORBIDDEN';
  end if;

  if nullif(trim(p_reason),'') is null then
    raise exception 'REJECTION_REASON_REQUIRED';
  end if;

  select * into v_purchase
  from public.points_purchase
  where id=p_purchase_id
  for update;

  if v_purchase.id is null then raise exception 'PURCHASE_NOT_FOUND'; end if;
  if v_purchase.status <> 'PENDING' then raise exception 'PURCHASE_NOT_PENDING'; end if;

  update public.points_purchase
  set status='REJECTED',
      rejection_reason=trim(p_reason),
      reviewed_at=now(),
      reviewed_by=public.current_admin_id(),
      updated_at=now()
  where id=v_purchase.id
  returning * into v_purchase;

  insert into public.operation(
    operation_key,operation_type,actor_type,actor_id,
    entity_type,entity_id,status,idempotency_key,completed_at
  )
  values(
    public.generate_public_code('OP'),'REJECT_PURCHASE','ADMIN',
    public.current_admin_id(),'points_purchase',v_purchase.id,
    'COMPLETED',p_idempotency_key,now()
  )
  returning id into v_operation;

  insert into public.notification_event(event_type,source_type,source_id)
  values('POINTS_PURCHASE_REJECTED','points_purchase',v_purchase.id);

  insert into public.audit_log(
    actor_type,actor_id,operation_id,entity_type,entity_id,action,
    permission_code,after_state,reason
  )
  values(
    'ADMIN',public.current_admin_id(),v_operation,
    'points_purchase',v_purchase.id,'REJECT_PURCHASE',
    'points_purchases.reject',to_jsonb(v_purchase),p_reason
  );

  return jsonb_build_object(
    'purchase_id',v_purchase.id,
    'status',v_purchase.status,
    'reason',v_purchase.rejection_reason
  );
end;
$$;

-- ================================================================
-- MARK NOTIFICATION READ
-- ================================================================

create or replace function public.mark_notification_read(
  p_notification_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id uuid;
begin
  select cp.id into v_customer_id
  from public.customer_profile cp
  join public.auth_account aa on aa.id=cp.auth_account_id
  where aa.auth_user_id=auth.uid();

  if v_customer_id is null then raise exception 'CUSTOMER_NOT_FOUND'; end if;

  update public.customer_notification
  set is_read=true,read_at=coalesce(read_at,now())
  where id=p_notification_id and customer_id=v_customer_id;

  if not found then raise exception 'NOTIFICATION_NOT_FOUND'; end if;

  return jsonb_build_object('notification_id',p_notification_id,'is_read',true);
end;
$$;

-- ================================================================
-- ADMIN GRANT POINTS
-- ================================================================

create or replace function public.admin_grant_points(
  p_customer_id uuid,
  p_amount bigint,
  p_reason text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance public.points_balance;
  v_operation uuid;
begin
  if not public.has_admin_permission('finance.write') then
    raise exception 'FORBIDDEN';
  end if;

  if p_amount <= 0 then raise exception 'INVALID_AMOUNT'; end if;
  if nullif(trim(p_reason),'') is null then raise exception 'REASON_REQUIRED'; end if;

  insert into public.points_balance(customer_id)
  values(p_customer_id)
  on conflict(customer_id) do nothing;

  select * into v_balance
  from public.points_balance
  where customer_id=p_customer_id
  for update;

  insert into public.points_ledger(
    customer_id,direction,amount,balance_before,balance_after,
    entry_type,source_type,description,created_by
  )
  values(
    p_customer_id,'CREDIT',p_amount,v_balance.balance,
    v_balance.balance+p_amount,'ADMIN_GRANT','admin_grant',
    p_reason,public.current_admin_id()
  );

  update public.points_balance
  set balance=balance+p_amount,updated_at=now()
  where id=v_balance.id;

  insert into public.operation(
    operation_key,operation_type,actor_type,actor_id,
    entity_type,entity_id,status,idempotency_key,completed_at
  )
  values(
    public.generate_public_code('OP'),'ADMIN_GRANT','ADMIN',
    public.current_admin_id(),'customer_profile',p_customer_id,
    'COMPLETED',p_idempotency_key,now()
  )
  returning id into v_operation;

  insert into public.audit_log(
    actor_type,actor_id,operation_id,entity_type,entity_id,action,
    permission_code,reason
  )
  values(
    'ADMIN',public.current_admin_id(),v_operation,
    'customer_profile',p_customer_id,'ADMIN_GRANT',
    'finance.write',p_reason
  );

  return jsonb_build_object(
    'customer_id',p_customer_id,
    'balance',v_balance.balance+p_amount
  );
end;
$$;

-- ================================================================
-- RLS
-- ================================================================

alter table public.auth_account enable row level security;
alter table public.customer_profile enable row level security;
alter table public.subscriber_identity enable row level security;
alter table public.admin_identity enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.admin_assignments enable row level security;
alter table public.telecom_company enable row level security;
alter table public.telecom_prefix enable row level security;
alter table public.protection_tariff enable row level security;
alter table public.task_configuration enable row level security;
alter table public.phone_number enable row level security;
alter table public.customer_number enable row level security;
alter table public.points_package enable row level security;
alter table public.payment_method enable row level security;
alter table public.points_balance enable row level security;
alter table public.points_purchase enable row level security;
alter table public.points_ledger enable row level security;
alter table public.number_protection_identity enable row level security;
alter table public.protection_period enable row level security;
alter table public.protection_extension enable row level security;
alter table public.task_plan enable row level security;
alter table public.periodic_task enable row level security;
alter table public.task_schedule_history enable row level security;
alter table public.task_execution enable row level security;
alter table public.financial_account enable row level security;
alter table public.expense_type enable row level security;
alter table public.financial_ledger enable row level security;
alter table public.expense enable row level security;
alter table public.financial_correction enable row level security;
alter table public.support_conversation enable row level security;
alter table public.support_message enable row level security;
alter table public.admin_message_thread enable row level security;
alter table public.admin_message enable row level security;
alter table public.notification_event enable row level security;
alter table public.customer_notification enable row level security;
alter table public.admin_notification_campaign enable row level security;
alter table public.admin_notification_recipient enable row level security;
alter table public.operation enable row level security;
alter table public.operation_idempotency enable row level security;
alter table public.audit_log enable row level security;
alter table public.app_content enable row level security;
alter table public.maintenance_config enable row level security;

-- Customer read policies.
create policy customer_profile_self_read on public.customer_profile
for select using (
  auth_account_id in (select id from public.auth_account where auth_user_id=auth.uid())
);

create policy subscriber_self_read on public.subscriber_identity
for select using (
  customer_profile_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy customer_number_self_read on public.customer_number
for select using (
  customer_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy phone_number_customer_read on public.phone_number
for select using (
  id in (
    select cn.phone_number_id from public.customer_number cn
    where cn.customer_id in (
      select cp.id from public.customer_profile cp
      join public.auth_account aa on aa.id=cp.auth_account_id
      where aa.auth_user_id=auth.uid()
    )
  )
);

create policy points_balance_self_read on public.points_balance
for select using (
  customer_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy points_purchase_self_read on public.points_purchase
for select using (
  customer_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy points_ledger_self_read on public.points_ledger
for select using (
  customer_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy protection_self_read on public.protection_period
for select using (
  customer_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy protection_identity_self_read on public.number_protection_identity
for select using (
  customer_number_id in (
    select cn.id from public.customer_number cn
    where cn.customer_id in (
      select cp.id from public.customer_profile cp
      join public.auth_account aa on aa.id=cp.auth_account_id
      where aa.auth_user_id=auth.uid()
    )
  )
);

create policy extension_self_read on public.protection_extension
for select using (
  protection_period_id in (
    select pp.id from public.protection_period pp
    where pp.customer_id in (
      select cp.id from public.customer_profile cp
      join public.auth_account aa on aa.id=cp.auth_account_id
      where aa.auth_user_id=auth.uid()
    )
  )
);

create policy customer_notifications_self_read on public.customer_notification
for select using (
  customer_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy customer_support_self_read on public.support_conversation
for select using (
  customer_id in (
    select cp.id from public.customer_profile cp
    join public.auth_account aa on aa.id=cp.auth_account_id
    where aa.auth_user_id=auth.uid()
  )
);

create policy customer_support_messages_read on public.support_message
for select using (
  conversation_id in (
    select sc.id from public.support_conversation sc
    where sc.customer_id in (
      select cp.id from public.customer_profile cp
      join public.auth_account aa on aa.id=cp.auth_account_id
      where aa.auth_user_id=auth.uid()
    )
  )
);

-- Public/reference reads for active configuration.
create policy telecom_company_active_read on public.telecom_company
for select using (status='ACTIVE');

create policy telecom_prefix_active_read on public.telecom_prefix
for select using (status='ACTIVE');

create policy tariff_active_read on public.protection_tariff
for select using (status='ACTIVE');

create policy task_config_active_read on public.task_configuration
for select using (status='ACTIVE');

create policy packages_visible_read on public.points_package
for select using (is_active=true and is_visible=true);

create policy payment_methods_visible_read on public.payment_method
for select using (is_active=true and is_visible=true);

create policy content_active_read on public.app_content
for select using (status='ACTIVE');

create policy maintenance_read on public.maintenance_config
for select using (true);

-- Admin read access is permission gated.
create policy admin_customer_read on public.customer_profile
for select using (public.is_admin());

create policy admin_number_read on public.customer_number
for select using (public.is_admin());

create policy admin_phone_read on public.phone_number
for select using (public.is_admin());

create policy admin_purchase_read on public.points_purchase
for select using (public.has_admin_permission('points_purchases.read'));

create policy admin_points_balance_read on public.points_balance
for select using (public.is_admin());

create policy admin_points_ledger_read on public.points_ledger
for select using (public.is_admin());

create policy admin_protection_read on public.protection_period
for select using (public.is_admin());

create policy admin_task_read on public.periodic_task
for select using (public.has_admin_permission('tasks.read'));

create policy admin_task_plan_read on public.task_plan
for select using (public.has_admin_permission('tasks.read'));

create policy admin_task_history_read on public.task_schedule_history
for select using (public.has_admin_permission('tasks.read'));

create policy admin_task_execution_read on public.task_execution
for select using (public.has_admin_permission('tasks.read'));

create policy admin_finance_read on public.financial_ledger
for select using (public.has_admin_permission('finance.read'));

create policy admin_expense_read on public.expense
for select using (public.has_admin_permission('finance.read'));

create policy admin_audit_read on public.audit_log
for select using (public.has_admin_permission('audit.read'));

-- No direct client INSERT/UPDATE/DELETE policies for sensitive domains.
-- Mutations must use RPCs.

-- ================================================================
-- GRANTS
-- ================================================================

grant usage on schema public to anon, authenticated;

grant select on
  public.telecom_company,
  public.telecom_prefix,
  public.protection_tariff,
  public.task_configuration,
  public.points_package,
  public.payment_method,
  public.app_content,
  public.maintenance_config
to authenticated;

grant select on
  public.customer_profile,
  public.subscriber_identity,
  public.customer_number,
  public.phone_number,
  public.points_balance,
  public.points_purchase,
  public.points_ledger,
  public.number_protection_identity,
  public.protection_period,
  public.protection_extension,
  public.support_conversation,
  public.support_message,
  public.customer_notification
to authenticated;

grant execute on function public.create_customer_profile(text,text) to authenticated;
grant execute on function public.ensure_auth_account() to authenticated;
grant execute on function public.add_customer_number(text,text) to authenticated;
grant execute on function public.submit_points_purchase(uuid,uuid,text,text) to authenticated;
grant execute on function public.approve_points_purchase(uuid,text) to authenticated;
grant execute on function public.reject_points_purchase(uuid,text,text) to authenticated;
grant execute on function public.mark_notification_read(uuid) to authenticated;
grant execute on function public.admin_grant_points(uuid,bigint,text,text) to authenticated;

-- ================================================================
-- VERIFICATION
-- ================================================================

do $$
declare
  required_count integer;
  actual_count integer;
begin
  select count(*) into actual_count
  from information_schema.tables
  where table_schema='public'
    and table_name in (
      'auth_account','customer_profile','subscriber_identity','admin_identity',
      'roles','permissions','role_permissions','admin_assignments',
      'telecom_company','telecom_prefix','protection_tariff','task_configuration',
      'phone_number','customer_number',
      'points_package','payment_method','points_purchase','points_balance','points_ledger',
      'number_protection_identity','protection_period','protection_extension',
      'task_plan','periodic_task','task_schedule_history','task_execution',
      'financial_ledger','expense','expense_type','financial_correction','financial_account',
      'support_conversation','support_message','admin_message_thread','admin_message',
      'notification_event','customer_notification','admin_notification_campaign',
      'admin_notification_recipient',
      'operation','operation_idempotency','audit_log',
      'app_content','maintenance_config'
    );

  required_count := 39;

  if actual_count <> required_count then
    raise exception 'AMAN_SCHEMA_VERIFICATION_FAILED: expected %, found %',required_count,actual_count;
  end if;
end $$;

commit;

-- ================================================================
-- END OF AMAN V11 SINGLE-FILE DATABASE
-- ================================================================
